version: '3'

services:

    backend:
        restart: always
        build: ./backend
        #ports:
        #  - "5000:5000"
        expose:
            - 5000
        depends_on:
            - mysqlcache
        command: sh -c "./gunicorn_starter.sh"
        environment:
            WAIT_HOSTS: "mysqlcache:3306"
            WAIT_HOSTS_TIMEOUT: 300
            WAIT_SLEEP_INTERVAL: 2
            WAIT_HOST_CONNECT_TIMEOUT: 2
            TZ: "Europe/Vienna"
            CACHE_DIR: "/cache"
        volumes:
            - "/docker_volume/backend_cache:/cache:rw"

    frontend:
        restart: always
        build: .
        ports:
            - 8003:80
        expose:
            - 8003
        depends_on:
            - backend
        environment:
            TZ: "Europe/Vienna"
