version: '3'

services:

    backend:
        restart: always
        build: ./backend
        #ports:
        #  - "5000:5000"
        expose:
            - 5000
        command: "python app.py"
        environment:
            TZ: "Europe/Vienna"
        volumes:
            - ".:/app"

    frontend:
        restart: always
        build: .
        ports:
            - 8003:80
        expose:
            - 8003
        depends_on:
            - backend
        environment:
            TZ: "Europe/Vienna"
