version: 1.4

jobs:
    update:
        cmd: "python /app/scripts/cache_queries.py update"
        onError: Continue
        time: "* 35 * * * *"
        notifyOnSuccess:
            - type: stdout
              data:
                - stdout
                - stderr
            - type: filesystem
              path: /jobber_logs/success
              data:
                - stdout
                - stderr
              maxAgeDays: 10
        notifyOnError:
            - type: stdout
              data:
                - stdout
                - stderr
            - type: filesystem
              path: /jobber_logs/errors
              data:
                - stdout
                - stderr
              maxAgeDays: 10

    fill:
        cmd: "python /app/scripts/cache_queries.py fill 2020-05-28"
        onError: Continue
        time: "* * 1 * * *"
        notifyOnSuccess:
            - type: stdout
              data:
                - stdout
                - stderr
            - type: filesystem
              path: /jobber_logs/success
              data:
                - stdout
                - stderr
              maxAgeDays: 10
        notifyOnError:
            - type: stdout
              data:
                - stdout
                - stderr
            - type: filesystem
              path: /jobber_logs/errors
              data:
                - stdout
                - stderr
              maxAgeDays: 10
